<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <link name="base_footprint" />

    <link name="base_link"> 
        <visual>
            <geometry>
                <box size= "${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0" />
            <material name="white" />
        </visual>
        <collision>
            <geometry>
                <box size= "${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="50.0" l="${6*base_length}" w="${6*base_width}" h="${6*base_height}"
                           xyz="0 0 0.1"  rpy="0 0 0" />
    </link >

    <link name ="lidar">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="white" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.1" length="0.05" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
         <xacro:cylinder_inertia m="15.0" r="0.6" h="0.3" xyz="0 0 0" rpy="0 0 0" />
    </link>

    <!--   adding a medi box -->
     <link name ="medi_box">
        <visual>
            <geometry>
                <box size = "0.5 0.3 0.1"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size = "0.5 0.3 0.1"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="15.0" l="3.0" w="1.8" h="0.6"
                           xyz="0 0 0"  rpy="0 0 0" />
    </link>
    <!--  end of a medi box -->

    <!--  Start of wheel function -->
    <xacro:macro name="wheel" params="prefix">
            <link name ="${prefix}_wheel">
                <visual>
                    <geometry>
                        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                    </geometry>
                    <origin xyz="0 0 0" rpy="1.57 0 0" />
                    <material name="red"/>
                </visual>
                <collision>
                    <geometry>
                        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                    </geometry>
                    <origin xyz="0 0 0" rpy="1.57 0 0" />
                </collision>
                <xacro:cylinder_inertia m="10.0" r="${6*wheel_radius}" h="${6*wheel_length}" xyz="0 0 0" rpy="1.57 0 0" />
            </link>
    </xacro:macro>
    <!--  End of wheel function -->

    <xacro:wheel prefix="left" />
    <xacro:wheel prefix="right" />
    <xacro:wheel prefix="front_left" />
    <xacro:wheel prefix="front_right" />

    <!--   joints section  -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0.1" rpy="0 0 0" />
    </joint>

    <joint name="base_lidar_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar" />
        <origin xyz="0.1 0 0.325" rpy="0 0 0" />
    </joint>

     <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <origin xyz="-0.15 0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin xyz="${-base_length / 4.0} -0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <!--   joint for medi box  -->
    <joint name="base_medi_box" type="fixed">
        <parent link="base_link" />
        <child link="medi_box" />
        <origin xyz="0 0 0.25" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <!--   joint for medi box  -->

    <!--   adding a front side wheel -->
    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel" />
        <origin xyz="${base_length / 4.0} 0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel" />
        <origin xyz="${base_length / 4.0} -0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>
    <!--   adding a front side wheel -->

</robot>